# Generated by Django 6.0 on 2025-12-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_album_cover_photo_alter_album_event_albumimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/album_covers/'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.album'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/event_covers/'),
        ),
    ]
