# Generated by Django 6.0 on 2026-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
