# Generated by Django 6.0 on 2025-12-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
    ]
