# Generated by Django 6.0 on 2025-12-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='media/images/original/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/watermarked/'),
        ),
    ]
